-- E-Mail-Eingang per POP3/IMAP (Stefan 2026-08-27)
ALTER TABLE "Tenant" ADD COLUMN "mailInPop3Enabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Tenant" ADD COLUMN "mailInPop3Host" TEXT;
ALTER TABLE "Tenant" ADD COLUMN "mailInPop3Port" INTEGER NOT NULL DEFAULT 995;
ALTER TABLE "Tenant" ADD COLUMN "mailInPop3Secure" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Tenant" ADD COLUMN "mailInPop3User" TEXT;
ALTER TABLE "Tenant" ADD COLUMN "mailInPop3Pass" TEXT;

ALTER TABLE "Tenant" ADD COLUMN "mailInImapEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Tenant" ADD COLUMN "mailInImapHost" TEXT;
ALTER TABLE "Tenant" ADD COLUMN "mailInImapPort" INTEGER NOT NULL DEFAULT 993;
ALTER TABLE "Tenant" ADD COLUMN "mailInImapSecure" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Tenant" ADD COLUMN "mailInImapUser" TEXT;
ALTER TABLE "Tenant" ADD COLUMN "mailInImapPass" TEXT;
ALTER TABLE "Tenant" ADD COLUMN "mailInImapFolder" TEXT;
ALTER TABLE "Tenant" ADD COLUMN "mailInImapMoveToFolder" TEXT;
